### ISSUE TITLE
Badge Alura Challenge

### ISSUE THREAD

**Issue by LucasdeFreitasp** [Walter-Alipio/Alura-dev-challenge#1]
Olá, frontender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nessa segunda edição do Challenge de Front-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essas badges 🏅 
 
Abraços e te vejo nos próximos Challenges!
![Badge - Github](https://user-images.githubusercontent.com/79534537/151362389-29164cd8-b1ef-43d0-b239-f7bfaef98888.png)
![Badge - Linkedin](https://user-images.githubusercontent.com/79534537/151362841-cabbfbfa-571d-4f77-bd6a-c7601718f38c.png)

**Comment by Walter-Alipio** [comment]
Sensacional! Valeu!
